### ISSUE TITLE
array_diff_key() and invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by quinnanya** [backdrop-contrib/biblio#4] opened 2020-11-23 23:19 UTC
I'm getting this error message on many of the administration pages with Biblio on a site upgraded from D7. Currently running Backdrop 1.17.3:

    Warning: array_diff_key(): Argument #1 is not an array in biblio_token_info() (line 12 of /home/modernis/backdropv2.modernistarchives.com/modules/biblio/biblio.tokens.inc).
    Warning: Invalid argument supplied for foreach() in biblio_token_info() (line 18 of /home/modernis/backdropv2.modernistarchives.com/modules/biblio/biblio.tokens.inc).

**Comment by olafgrabienski** [comment] 2020-12-22 22:27
Confirmed: I see these messages in DBlog of a quite fresh Backdrop site (no D7 upgrade).

**Comment by jenlampton** [comment] 2021-02-07 04:42
> I'm getting this error message on many of the administration pages with Biblio

Biblio itself doesn't have any administration pages (since it now uses nodes and feeds and other existing Backdrop tools). Can you be more specific as to where you are seeing these errors? (URLs would be ideal)

**Comment by quinnanya** [comment] 2021-02-08 06:17
Here's one of the pages, and a screenshot: /admin/structure/taxonomy/biblio_pub_type/add
<img width="1072" alt="Screen Shot 2021-02-07 at 10 15 56 PM" src="https://user-images.githubusercontent.com/712016/107182794-4644fc80-6992-11eb-84bf-537a1ca1e263.png">

**Comment by olafgrabienski** [comment] 2021-02-08 08:58
@jenlampton The warnings were on regular admin pages (not specific to Biblio), e.g. `admin/modules` or `admin/structure/types`.

**Comment by jenlampton** [comment] 2021-02-08 19:35
Thanks! this is really helpful :) Looks like maybe the problem is with Biblio tokens, I'll start there :)

**Comment by jenlampton** [comment] 2024-02-19 20:03
This fix was merged and can be seen in 2095dbd6. Closing.

**Comment by irinaz** [comment] 2024-03-03 23:07
@jenlampton , 
I installed module Biblio on core 1.26 and I am getting the following error on php8.1.  
Module installs   on php7 with warning message

```
Error
Error message
Warning: Trying to access array offset on value of type bool in biblio_token_info() (line 12 of /Users/irinazaks/Sites/localhost/4-fibo/modules/biblio/biblio.tokens.inc).
TypeError: array_diff_key(): Argument #1 ($array) must be of type array, null given in array_diff_key() (line 12 of /Users/irinazaks/Sites/localhost/4-fibo/modules/biblio/biblio.tokens.inc).
Dismissarray_diff_key(): Argument #1 ($array) must be of type array, null given
```

**Comment by irinaz** [comment] 2024-03-04 03:12
@jenlampton , is it possible that there is no release that includes this bug fix?

**Comment by jenlampton** [comment] 2024-07-10 18:48
@irinaz You can tell by looking at the merge date (Feb 19, 2024) and then the latest release date Feb 6, 2021.  Or, by testing the -dev version. 

Looks like it's time for a new release!  I'm going to review the queue and will see what else we can get fixed. Closing again.

**Closed as completed by jenlampton** 2024-07-10 18:48 UTC
